---
title: "bayesian_R"
output: pdf_document
date: "2026-04-2"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r install}
#install.packages("geoR")
install.packages("mvnfast")
```


```{r load}
library(mvnfast)
```

```{r helper-functions}
rinvchisq <- function(n, df, scale) {
  (df * scale) / rchisq(n, df = df)}

```


```{r load-data}
preds <- read.csv("predictions.csv")
head(preds)
str(preds)
```

```{r clean-data}
# rename cols
colnames(preds) <- c("true", "pred", "prob", "correct")

# checks 
str(preds)
preds$correct <- as.numeric(preds$correct)
head(preds)
```

```{r matrices}
# outcome variable
y <- preds$correct

# design matrix: intercept + cnn prob
X <- cbind(1, preds$prob)

# checks
dim(X)
length(y)

head(X)
head(y)
```


```{r ols}
# ordinary least sqrs estimate
w_hat <- solve(t(X) %*% X) %*% t(X) %*% y

w_hat
```


```{r bayesian}
# prior
lambda <- 1 

# identity matrix
I <- diag(ncol(X))

# posterior covariance
Sigma_post <- solve(t(X) %*% X + lambda * I)

# posterior mean
mu_post <- Sigma_post %*% t(X) %*% y

mu_post
```



```{r posterior-sampling}
set.seed(1)

# num samples + draw from posterior
n_samples <- 1000

samples <- rmvn(n_samples, mu = as.vector(mu_post), sigma = Sigma_post)

# check
head(samples)
```


```{r summarize-posterior}
# mean samples
colMeans(samples)

# standard dev - uncertainty
apply(samples, 2, sd)

# 95% intervals
apply(samples, 2, quantile, probs = c(0.025, 0.975))
```


```{r plot}
plot(jitter(preds$prob),
     jitter(preds$correct, amount = 0.05),
     xlab = "CNN Confidence",
     ylab = "Correct (0/1)",
     main = "CNN Confidence vs Accuracy",
     pch = 16,
     cex = 0.4)   # smaller points

abline(a = mu_post[1], b = mu_post[2], col = "red", lwd = 2)
```

```{r folds}
run_bayesian_fold <- function(file_name) {
  preds <- read.csv(file_name)
  colnames(preds) <- c("true", "pred", "prob", "correct")
  preds$correct <- as.numeric(preds$correct)
  
  y <- preds$correct
  X <- cbind(1, preds$prob)
  
  # ols
  #w_hat <- solve(t(X) %*% X + 1e-6 * diag(ncol(X))) %*% t(X) %*% y
  
  # posterior
  lambda <- 1
  I <- diag(ncol(X))
  Sigma_post <- solve(t(X) %*% X + lambda * I)
  mu_post <- Sigma_post %*% t(X) %*% y
  
  # posterior sampling
  set.seed(1)
  n_samples <- 1000
  samples <- rmvn(n_samples, mu = as.vector(mu_post), sigma = Sigma_post)
  
  # summarize
  means <- colMeans(samples)
  sds <- apply(samples, 2, sd)
  cis <- apply(samples, 2, quantile, probs = c(0.025, 0.975))
  
  list(
    file = file_name,
    w_hat = w_hat,
    mu_post = mu_post,
    means = means,
    sds = sds,
    cis = cis
  )
}
```

```{r fold-results}
fold1_results <- run_bayesian_fold("predictions_1fold.csv")
fold2_results <- run_bayesian_fold("predictions_2fold.csv")
```

```{r}
fold1_results
```

```{r}
fold2_results
```
